### ISSUE TITLE
check grant  agreement for primary data sets

### ISSUE THREAD

**Issue by benjaminpfeil** [ArcticPASSION/DataManagementPlan#1]
Often WP and tasks leads do not give feedback - it may be worth to check all deliverables and milestones if they will result in primary ArcticPassion datasets.

**Comment by steingod** [comment]
@elfsprite , I assign this to you  but will also contribute. Ok?

**Comment by elfsprite** [comment]
it is ok!

> @elfsprite , I assign this to you but will also contribute. Ok?

**Comment by steingod** [comment]
Closing this as table 1 of DMP was based on this, however GA is insufficient on details so continuing with a questionnaire.
