### ISSUE TITLE
Update datasets 

### ISSUE THREAD

**Issue by ferrighi** [ArcticPASSION/DataManagementPlan#5]
Update the DMP with records registered through the webform submissions from https://data.arcticobserving.org/, this includes datasets collected or producted, but also used in the pilot service.

**Comment by steingod** [comment]
Will update with the new records, have to change structure slightly.

**Comment by steingod** [comment]
This is now part of the branch updateGA2024.

**Comment by steingod** [comment]
Closing this as part of #6
